### ISSUE TITLE
How can I translate it? It's not in the Flarum Core.

### ISSUE THREAD

**Issue by JeongJun-Lee** [flarum-lang/uzbek#2]
How can I translate it? It's not in the Flarum Core.

![image](https://user-images.githubusercontent.com/11474775/143525655-4de3baca-98c5-41f7-b511-b20ccb3d68a3.png)

![image](https://user-images.githubusercontent.com/11474775/143525796-60d68228-73a5-4752-b05d-0e1524c70621.png)

**Comment by luceos** [comment]
From the second image, these keys are from extensions. For instance the "edit tags" comes from the Flarum Tags extension, see: https://weblate.rob006.net/projects/flarum/flarum-tags/uz/, all extensions are listed here: https://weblate.rob006.net/languages/uz/flarum/#overview

For the dates, this is something that leans on dayjs, see https://docs.flarum.org/extend/language-packs#dayjs-translations. One of our @flarum-lang/language-coordinators  should be able to get you started with that.

**Comment by justoverclockl** [comment]
feel free to ask if you need more support

**Comment by JeongJun-Lee** [comment]
I made a [pr](https://github.com/flarum-lang/uzbek/pull/3) for dayjs. Is it enough? pls review and merge it. Thanks.
